name: vhv_shared
description: "A new Flutter project."
version: 0.0.1
homepage: "https://vhv.vn"
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  device_info_plus: ^12.2.0
  mobile_device_identifier: ^0.0.3
  logger: ^2.6.2
  collection: ^1.18.0
  equatable: ^2.0.7
  dotted_border: ^3.1.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  bot_toast: ^4.1.3
  easy_localization: ^3.0.8
  nested:
  flutter_svg: ^2.2.3
  flutter_widget_from_html: ^0.17.0
  crypto: ^3.0.7
  go_router: ^17.0.0
  archive: ^4.0.7
  responsive_builder: ^0.7.1
  loader_overlay: ^5.0.0
  html: ^0.15.6
  bottom_sheet:
    path: ../../3rdparty/bottom_sheet-4.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
#flutter_intl:
#  enabled: true # Required. Must be set to true to activate the package. Default: false
#  class_name: VHVSharedStrings # Optional. Sets the name for the generated localization class. Default: S
#  main_locale: vi # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
#  arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
#  output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
#  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
flutter:
  fonts:
    - family: vhv
      fonts:
        - asset: fonts/vhv.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter_18pt-Thin.ttf
          weight: 100
        - asset: fonts/Inter/Inter_18pt-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Inter/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter/Inter_18pt-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: fonts/Inter/Inter_18pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: fonts/Inter/Inter_18pt-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: fonts/Inter/Inter_18pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter/Inter_18pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: fonts/Inter/Inter_18pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Inter/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter/Inter_18pt-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Inter/Inter_18pt-Black.ttf
          weight: 900
        - asset: fonts/Inter/Inter_18pt-BlackItalic.ttf
          weight: 900
          style: italic
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/file-icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
