name: vhv_widgets
description: "A new Flutter project."
version: 0.0.1
homepage: "https://vhv.vn"
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter


  vhv_shared:
    path: ../vhv_shared
  vhv_state:
    path: ../vhv_state
  vhv_config:
    path: ../vhv_config
  vhv_utils:
    path: ../vhv_utils
  vhv_navigation:
    path: ../vhv_navigation
  vhv_network:
    path: ../vhv_network
  vhv_storage:
    path: ../vhv_storage

  flutter_html: ^3.0.0
  flutter_html_all: ^3.0.0

  flutter_inappwebview: ^6.0.0
  flutter_widget_from_html: ^0.17.0
  cached_network_image: ^3.3.1
  file_picker: ^10.2.0
  image_picker: ^1.1.1
  pdfx: ^2.9.2
  url_launcher: ^6.3.2

  animations: ^2.1.1
  image_cropper: 9.1.0
  image: ^4.5.4
  card_swiper: ^3.0.1
  photo_view: ^0.15.0
  flutter_exif_rotation: ^0.5.1

  flutter_tagging_plus:
    path: ../3rdparty/flutter_tagging_plus-4.0.2
  html_unescape: ^2.0.0
  webview_flutter: ^4.13.0
  youtube_player_flutter: ^9.1.3
  just_audio: ^0.10.4
  video_player: ^2.10.0
  better_player:
    path: ../3rdparty/better_player
  wechat_assets_picker:
    path: ../3rdparty/wechat_assets_picker-9.8.0
  wechat_camera_picker:
    path: ../3rdparty/wechat_camera_picker-4.4.0
  camera: ^0.11.2
  rxdart:
  bottom_picker: ^4.1.1
  # html_editor:  # Commented out: circular dependency with vhv_core
  #   path: ../3rdparty/flutter_html_editor_new
  flutter_datetime_picker_plus:
    path: ../3rdparty/flutter_datetime_picker_plus-2.2.0
#  html_editor:
#    path: ../3rdparty/flutter_html_editor
  calendar_date_picker2: ^2.0.1
  syncfusion_flutter_datepicker: ^30.1.39

  dropdown_button2: ^2.3.9
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.4.1
  flutter_speed_dial: ^7.0.0
  vs_scrollbar: ^1.0.0
  html: ^0.15.6




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
