name: flutter_neat_and_clean_calendar
description: >-
  Simple and clean flutter calendar with ability to  slide up/down to show
  weekly/monthly calendar.  Fork of
  https://pub.dev/packages/flutter_clean_calendar
version: 0.3.14+32
homepage: https://github.com/rwbr/flutter_neat_and_clean_calendar
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  macos_ui: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
